# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "Example1"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Setup
    export DEBIAN_FRONTEND="noninteractive"
    export TERM="xterm"
    # Start up
    apt-get update
    # Essential tools
    apt-get install -y vim tmux screen curl nfs-common
    # bear
    sudo apt-get install -y openvpn  
  SHELL
end
